login:
    path: /login
    defaults: { _controller: AppBundle:User:login}
    
login_check:
    path: /login_check

logout:
    path: /logout
    
    
register:
    path: /register
    defaults: { _controller: AppBundle:User:register}
    
user_nick_test:
    path: /nick-test
    defaults: { _controller: AppBundle:User:nickTest}
    methods: [POST]
    
user_edit:
    path: /my-data
    defaults: { _controller: AppBundle:User:editUser }
    
users_list:
    path: /publicaciones
    defaults: { _controller: AppBundle:User:usuarios }
    
users_search:
    path: /search
    defaults: { _controller: AppBundle:User:search }  
    
    
user_perfil:
    path: /perfil/{nick}
    defaults: { _controller: AppBundle:User:perfil, nick:null}

user_admin:
    path: /admin
    defaults: { _controller: AppBundle:User:admin}

user_borra:
    path: /borra/{id}
    defaults: { _controller: AppBundle:User:borraUsuario, id:null}