BackendBundle\Entity\Comentarios:
    type: entity
    table: comentarios
    indexes:
        fk_comentarios_usuarios:
            columns:
                - receptor
                
        fk_comentarios_emisor:
            columns:
                - emisor
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        comentario:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
                
        nota:
            type: integer
            nullable: true
            length: 255
            options:
                fixed: false        
        
        fecha:
            type: datetime
            nullable: true
            length: 255
            options:
                fixed: false            
                
    manyToOne:
        publicacion:
            targetEntity: Publicacion
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                publicacion:
                    referencedColumnName: id
            orphanRemoval: false
        emisor:
            targetEntity: Usuario
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                emisor:
                    referencedColumnName: id
            orphanRemoval: false
            
        receptor:
            targetEntity: Usuario
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                receptor:
                    referencedColumnName: id
            orphanRemoval: false    
    lifecycleCallbacks: {  }
