BackendBundle\Entity\Publicacion:
    type: entity
    table: publicaciones
    indexes:
        fk_publicaciones_usuarios:
            columns:
                - usuario_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        
        tipo:
            type: string
            nullable: true
            length: 7
            options:
                fixed: false
        
        usuario_id:
            type: integer
            nullable: true
            options:
                fixed: false
                
        text:
            type: text
            nullable: true
            length: 16777215
            options:
                fixed: false
        documento:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
        imagen:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        estado:
            type: string
            nullable: true
            length: 30
            options:
                fixed: false
        createtAt:
            type: datetime
            nullable: true
            column: createt_at
        diaLibre:
            type: datetime
            nullable: true
            column: dia_libre
        horaInicio:
            type: datetime
            nullable: true
            column: hora_inicio
        horaFin:
            type: datetime
            nullable: true
            column: hora_fin
            
        asunto:
            type: text
            nullable: true
            length: 16777215
            options:
                fixed: false    
                
        mensajes:
            type: integer
            nullable: true
            length: 7
            options:
                fixed: false
                
        cerrada:
            type: integer
            nullable: true
            options:
                fixed: false    
                
        provincia:
            type: text
            nullable: true
            length: 16777215
            options:
                fixed: false    
    manyToOne:
        usuario:
            targetEntity: Usuario
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                usuario_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
